spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/postgres
    username: ev
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show-sql: true
        jdbc:
          batch_size: 5
          order_inserts: true
        generate_statistics: true

server:
  port: 8082